# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build
  build:
    # The type of runner that the job will run
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: adf_publish
   #   - name: Install Az PowerShell module
    #    run: if('${{ inputs.skipAzModuleInstallation }}' -ne 'true') { Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force }
     #   shell: pwsh
      # - name: Azure CLI Login
      #   run: az login
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v2
        with:
          client-id: 44ce4d40-3a24-4af1-a1f8-48595467f379
          tenant-id: d761e4c1-1cf1-4a04-be8d-709671979248
          subscription-id: 4687c1ca-c1ae-47e0-ae76-60a68ee370d3
          client-secret: VK48Q~ji4CqvFV-vHfpILzJ7w3ewjTvkuCyErb1k
          enable-AzPSSession: true
  #    - name: Azure Blob Upload
  # You may pin to the exact commit or the version.
  # uses: LanceMcCarthy/Action-AzureBlobUpload@ce90b2d1f7a7f0ddf7402d6be82efe0fb5c34283
   #     uses: LanceMcCarthy/Action-AzureBlobUpload@v3.1.2
 #       with:
    # Azure Storage ConnectionString for the container (Azure Portal - select Storage Account - Access Keys blade).
     ##     connection_string: DefaultEndpointsProtocol=https;AccountName=teststorageadf9999;AccountKey=rCAyldQUU/vXxi3ZcIOQN9EX7F1fsuafADcX4GQJjwyhpI/YPc12YrkWDUrq6W9izJBCt/GLiM51+AStoJmn+g==;EndpointSuffix=core.windows.net
    # Blob Container name (e.g. my-container).
         # container_name: test
    # The local folder containing all the files and subfolders to upload to the blob container (use a trailing slash).
       #   source_folder: adfdevesha
    # The target folder to use in the blob container with (do not use a leading or trail
        #  is_recursive: true
    # If the blob exists it will be skipped, unless this is set to true.
    
          
          
      - name: Run Pre-deployment script
        shell: pwsh
        run: pwsh adfdevesha/trigger.ps1 -armTemplate adfdevesha/ARMTemplateForFactory.json  -ResourceGroupName testrg -DataFactoryName datafactoryesha -predeployment:$True -deleteDeployment:$False
      
     # - name: data-factory-deploy
      #  uses: Azure/data-factory-deploy-action@v1.2.0
       # with:
          # Data Factory resource group name
        #  resourceGroupName: testrg
          # Data factory name
         # dataFactoryName: datafactoryesha
    # ARM template file name
          #armTemplateFile: https://teststorageadf9999.blob.core.windows.net/test/ARMTemplateForFactory.json?sp=racwdyti&st=2024-06-25T06:57:26Z&se=2024-06-25T14:57:26Z&spr=https&sv=2022-11-02&sr=b&sig=JfgmGZ7EY%2BgDHZyVxsZMB6djzDdyaicD62WcmHH%2B%2F9c%3D
    # ARM template parameters file name
          #armTemplateParametersFile: https://teststorageadf9999.blob.core.windows.net/test/ARMTemplateParametersForFactory.json?sp=racwdyti&st=2024-06-25T06:58:43Z&se=2024-06-25T14:58:43Z&spr=https&sv=2022-11-02&sr=b&sig=Z8n4%2BYEJACNZ8l2X3Cf7v2cu522PVM4%2BFZxVsWQRIxs%3D
    # Parameters which will be replaced in the ARM template
          #additionalParameters: 'factoryName=datafactoryesha containerUri=https://teststorageadf9999.blob.core.windows.net/test containerSasToken=?sp=racwdli&st=2024-06-25T07:00:59Z&se=2024-06-25T15:00:59Z&spr=https&sv=2022-11-02&sr=c&sig=cCG9iDIoMb6lu6dl3vgEaA7EcnH7eFXZJXw2%2BGOwL0g%3D '
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v2
        with:
    # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'tenant', 'managementgroup', 'subscription'
         scope: resourcegroup
    # Override the Subscription Id set by Azure Login.
         subscriptionId: 4687c1ca-c1ae-47e0-ae76-60a68ee370d3
   
    
    # Provide the name of a resource group, only required for resource Group deployments.
         resourceGroupName: testrg
    # Specify the path or URL to the Azure Resource Manager template.
         template: adfdevesha/ARMTemplateForFactory.json
    
         parameters: adfdevesha/ARMTemplateParametersForFactory.json  factoryName=datafactoryesha 
    
        # additionalArguments: 'factoryName=datafactoryesha containerUri=https://teststorageadf9999.blob.core.windows.net/test/linkedTemplates containerSasToken=?sp=racwdli&st=2024-06-25T07:00:59Z&se=2024-06-25T15:00:59Z&spr=https&sv=2022-11-02&sr=c&sig=cCG9iDIoMb6lu6dl3vgEaA7EcnH7eFXZJXw2%2BGOwL0g%3D '
          
      - name: Run Pre-deployment script
        shell: pwsh
        run: pwsh adfdevesha/trigger.ps1 -armTemplate adfdevesha/ARMTemplateForFactory.json  -ResourceGroupName testrg -DataFactoryName datafactoryesha -predeployment:$False -deleteDeployment:$True
      
    
          
